import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function AccountOrdersPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/admin/login");
  const { data: orders } = await supabase.from("orders").select("id,order_number,status,grand_total,created_at,order_items(product_name,size,color,quantity,line_total),shipments(status,awb_code,courier_name,tracking_url)").eq("user_id", user.id).order("created_at", { ascending: false });
  return <main className="min-h-screen bg-[var(--background)] px-5 py-10"><div className="mx-auto max-w-4xl"><Link href="/shop" className="text-sm font-semibold">← Continue shopping</Link><p className="mt-8 text-xs font-bold uppercase tracking-[0.3em] text-[var(--accent)]">GJC ACCOUNT</p><h1 className="mt-2 text-4xl font-black">My orders</h1><div className="mt-8 space-y-5">{(orders??[]).map((o:any)=><article key={o.id} className="rounded-3xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold">{o.order_number}</p><p className="mt-1 text-xs text-black/45">{new Date(o.created_at).toLocaleString("en-IN")}</p></div><div className="text-right"><p className="font-black">₹{Number(o.grand_total).toLocaleString("en-IN")}</p><span className="mt-1 inline-block rounded-full bg-black/[0.05] px-3 py-1 text-xs font-semibold">{o.status}</span></div></div><div className="mt-5 border-t pt-5 space-y-2 text-sm">{(o.order_items??[]).map((i:any)=><div key={`${i.product_name}-${i.size}-${i.color}`} className="flex justify-between gap-4"><span>{i.product_name} × {i.quantity} {i.size?`· ${i.size}`:""} {i.color?`· ${i.color}`:""}</span><span>₹{Number(i.line_total).toLocaleString("en-IN")}</span></div>)}</div>{(Array.isArray(o.shipments)?o.shipments[0]:o.shipments)?.awb_code && <div className="mt-5 rounded-2xl bg-[#f7f3ec] p-4"><p className="text-xs font-bold uppercase tracking-wide text-black/45">Shipment</p><p className="mt-1 text-sm font-semibold">{(Array.isArray(o.shipments)?o.shipments[0]:o.shipments).courier_name || "Courier"} · AWB {(Array.isArray(o.shipments)?o.shipments[0]:o.shipments).awb_code}</p><a href={(Array.isArray(o.shipments)?o.shipments[0]:o.shipments).tracking_url || `https://shiprocket.co/tracking/${(Array.isArray(o.shipments)?o.shipments[0]:o.shipments).awb_code}`} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-bold underline">Track shipment</a></div>}</article>)}{!orders?.length&&<div className="rounded-3xl border border-dashed p-12 text-center text-sm text-black/50">No orders yet.</div>}</div></div></main>;
}
