import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/account");
  const { data: order } = await supabase.from("orders").select("id,order_number,status,currency,subtotal,discount_total,shipping_total,tax_total,grand_total,shipping_address,created_at,updated_at,order_items(product_name,sku,size,color,unit_price,quantity,line_total),shipments(provider,awb_code,courier_name,tracking_url,status)").eq("id", id).eq("user_id", user.id).maybeSingle();
  if (!order) notFound();
  const address = order.shipping_address as any;
  const shipment = Array.isArray(order.shipments) ? order.shipments[0] : order.shipments;
  const steps = ["pending", "confirmed", "processing", "shipped", "delivered"];
  const current = steps.indexOf(order.status);
  return <main className="min-h-screen bg-[var(--background)] px-5 py-10"><div className="mx-auto max-w-4xl"><Link href="/account/orders" className="text-sm font-semibold">← My orders</Link><div className="mt-8 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-[var(--accent)]">ORDER</p><h1 className="mt-2 text-4xl font-black">{order.order_number}</h1><p className="mt-2 text-sm text-black/50">Placed {new Date(order.created_at).toLocaleString("en-IN")}</p></div><span className="rounded-full bg-black px-4 py-2 text-xs font-bold uppercase text-white">{order.status}</span></div>
    <section className="mt-8 rounded-3xl border bg-white p-6"><h2 className="text-lg font-black">Order status</h2><div className="mt-6 grid grid-cols-5 gap-2">{steps.map((step,i)=><div key={step} className="text-center"><div className={`mx-auto h-3 w-3 rounded-full ${i<=current?"bg-[#171717]":"bg-black/10"}`}/><p className="mt-2 text-[11px] font-semibold capitalize text-black/60">{step}</p></div>)}</div></section>
    <section className="mt-5 rounded-3xl border bg-white p-6"><h2 className="text-lg font-black">Items</h2><div className="mt-4 space-y-4">{(order.order_items??[]).map((item:any)=><div key={`${item.product_name}-${item.sku}-${item.size}-${item.color}`} className="flex justify-between gap-5 border-b pb-4 last:border-0 last:pb-0"><div><p className="font-bold">{item.product_name}</p><p className="mt-1 text-xs text-black/45">Qty {item.quantity}{item.size?` · ${item.size}`:""}{item.color?` · ${item.color}`:""}</p></div><p className="font-bold">₹{Number(item.line_total).toLocaleString("en-IN")}</p></div>)}</div><div className="mt-5 space-y-2 border-t pt-5 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>₹{Number(order.subtotal).toLocaleString("en-IN")}</span></div><div className="flex justify-between"><span>Shipping</span><span>₹{Number(order.shipping_total).toLocaleString("en-IN")}</span></div><div className="flex justify-between"><span>Tax</span><span>₹{Number(order.tax_total).toLocaleString("en-IN")}</span></div><div className="flex justify-between pt-2 text-base font-black"><span>Total</span><span>₹{Number(order.grand_total).toLocaleString("en-IN")}</span></div></div></section>
    <div className="mt-5 grid gap-5 sm:grid-cols-2"><section className="rounded-3xl border bg-white p-6"><h2 className="text-lg font-black">Shipping address</h2>{address?<p className="mt-3 text-sm leading-6 text-black/65">{address.full_name}<br/>{address.address_line1}{address.address_line2?<><br/>{address.address_line2}</>:null}<br/>{address.city}, {address.state} {address.postal_code}<br/>{address.country}<br/>{address.phone}</p>:<p className="mt-3 text-sm text-black/50">Address unavailable.</p>}</section><section className="rounded-3xl border bg-white p-6"><h2 className="text-lg font-black">Shipment</h2>{shipment?.awb_code?<><p className="mt-3 text-sm font-semibold">{shipment.courier_name||shipment.provider||"Courier"}</p><p className="mt-1 text-sm text-black/55">AWB: {shipment.awb_code}</p><p className="mt-1 text-sm text-black/55">Status: {shipment.status||"In transit"}</p><a className="mt-4 inline-block text-sm font-bold underline" href={shipment.tracking_url||`https://shiprocket.co/tracking/${shipment.awb_code}`} target="_blank" rel="noreferrer">Track shipment →</a></>:<p className="mt-3 text-sm text-black/50">Shipment tracking will appear after dispatch.</p>}</section></div>
  </div></main>;
}
